FROM jinnlynn/alpine:armhf

MAINTAINER JinnLynn <eatfishlin@gmail.com>

ENV REDIR_SET GFWLIST
ENV REDIR_PORT 9528

RUN set -ex && \
    apk add --no-cache dnsmasq iptables ipset

COPY entrypoint.sh /app/bin/entrypoint

EXPOSE 53 53/udp 67/udp

ENTRYPOINT ["/app/bin/entrypoint"]

CMD ["dnsmasq", "-k", "--user=root", "--log-facility=-", "--conf-dir=/app/etc,*.conf"]
