FROM jinnlynn/alpine:armhf

MAINTAINER JinnLynn <eatfishlin@gmail.com>

ARG RAW_URL=https://github.com/lukas2511/dehydrated/raw/master/dehydrated

# alpine中的awk, grep等命令为busybox版本不适合dehydrated，需另外安装
RUN set -ex && \
    apk add --no-cache bash curl jq openssl gawk sed grep diffutils && \
    curl -SL -o /bin/dehydrated $RAW_URL && \
    chmod +x /bin/dehydrated

ENTRYPOINT ["dehydrated"]

CMD ["-h"]
