#!/bin/sh
set -ex

BRANCH="edge"
VERSION="3.7.0"
MIRROR="https://mirrors.ustc.edu.cn/alpine"
TIMEZONE="Asia/Shanghai"
APP_DIRS="bin etc opt tmp run log cache local"

if [ "$MIRROR" ]; then
    {
        echo "$MIRROR/$BRANCH/main"
        echo "$MIRROR/$BRANCH/community"
        if [ "$BRANCH" == "edge" ]; then
            echo "$MIRROR/$BRANCH/testing"
        fi
    } >/etc/apk/repositories
fi

if [ "$TIMEZONE" ]; then
    apk add --no-cache tzdata
    cp "/usr/share/zoneinfo/$TIMEZONE" "/etc/localtime"
    apk del --no-cache tzdata
fi

if [ "$APP_DIRS" ]; then
    # alpine mkdir 不支持mkdir -p /app/{...}
    for d in $APP_DIRS; do mkdir -p /app/$d; done
fi

exit 0
