FROM jinnlynn/alpine:armhf

LABEL maintainer="JinnLynn <eatfishlin@gmail.com>"

COPY deps/ /tmp/

RUN set -ex && \
    cd tmp && \
    tar xf arm-linux-gnueabihf.tar.gz -C /lib && \
    tar xf Xware1.0.31_armel_v5te_glibc.tar.gz -C /app/bin && \
    cp entrypoint /app/bin && \
    mkdir -p /app/run/cfg && \
    ln -s /app/run/cfg /app/bin/cfg && \
    rm -rf /tmp/*

VOLUME /app/run

CMD ["entrypoint"]
