FROM jinnlynn/python:armhf

MAINTAINER "JinnLynn <eatfishlin@gmail.com>"

ARG PKG=https://github.com/JinnLynn/genpac/archive/master.zip

RUN set -ex && \
    cd /tmp && \
    pip install --no-cache-dir $PKG && \
    rm -rf /tmp/*

CMD genpac -h
