#!/usr/bin/env sh
. ~/git-shell-commands/_common.sh

goto_git_repo_dir || exit 1

[ -n "$1" ] && {
    cd "$1" 2>/dev/null || exit 1
}

print_if_bare_repo='
    if "$(git --git-dir="$1" rev-parse --is-bare-repository)" = true
    then
        du -sh "${1#./}"
        # printf "%s\t%s\n" "${1#./}" "$(du -sh $1)"
    fi
'

find -maxdepth 1 -type d -name "*.git" -exec sh -c "$print_if_bare_repo" -- \{} \; -prune 2>/dev/null | \
    awk '{printf "%s|%s\n", $2, $1}' | \
    column -ts "|" | \
    sort
