#!/usr/bin/env sh
git_ver=$(git --version | awk '{print $3}')
alpine_ver=$(cat /etc/alpine-release)
echo
echo "Welcome to git server (git-v$git_ver alpine-v$alpine_ver)"
echo "You've successfully authenticated, but I do not"
echo "provide interactive shell access."
echo
exit 128
