#!/usr/bin/env sh
git_ver=$(git --version | awk '{print $3}')
alpine_ver=$(cat /etc/alpine-release)

cat <<EOF

Welcome to git server (git-v$git_ver alpine-v$alpine_ver)
You've successfully authenticated, but I do not
provide interactive shell access.

EOF

exit 128
