FROM jinnlynn/python:armhf

LABEL maintainer="JinnLynn <eatfishlin@gmail.com>"

ARG PKG=https://github.com/JinnLynn/genpac/archive/dev.zip

RUN set -ex && \
    pip install --no-cache-dir $PKG

ENTRYPOINT ["genpac"]

CMD ["-h"]
