# 翻墙 客户端 172.27.0.x
version: "3.8"
x-logging: &logging
    options:
        max-size: 10m
services:
    kcptun:
        image: jinnlynn/kcptun
        logging: *logging
        restart: always
        networks:
            freegate:
                ipv4_address: 172.27.0.10
        ports:
            - 12948:12948
            - 12948:12948/udp
        command: kcptun-client -r $KCPTUN_REMOTE $KCPTUN_ARGS
    redir:
        image: jinnlynn/shadowsocks
        logging: *logging
        restart: always
        network_mode: host #! 必须
        depends_on:
            - kcptun
        command: ss-redir $SS_SERVER $SS_AUTH $SS_ARGS -l 9528 --reuse-port
    dns-tunnel:
        image: jinnlynn/shadowsocks
        logging: *logging
        restart: always
        networks:
            - freegate
        ports:
            - 9553:1080/udp
        command: ss-tunnel $SS_SERVER $SS_AUTH $SS_ARGS -l 1080 -L 8.8.8.8:53
    freedom:
        image: jinnlynn/freedom
        logging: *logging
        restart: always #! 必须 没有退出时iptables添加的规则会被清空 WHY?
        privileged: true
        # sysctls:
        #     - net.ipv4.ip_forward=1
        network_mode: host
        environment:
            - REDIR_SERVER
        volumes:
            - ${KITS_LOCAL}/freedom:/app/local
        command: ["gfwlist", "keep-alive"]
    dnsmasq:
        image: jinnlynn/dnsmasq
        logging: *logging
        restart: always
        privileged: true
        network_mode: host
        depends_on:
            - dns-tunnel
            - redir
            - freedom
        volumes:
            - ${KITS}/etc/dnsmasq:/app/etc
            - ${KITS_LOCAL}/dnsmasq:/app/local
        command:
            - dnsmasq
            - -k
            - --user=root
            - --log-facility=-
            - --conf-dir=/app/etc,*.conf
            - --conf-file=/app/local/gfwlist.conf
            - --dhcp-leasefile=/app/local/dnsmasq.leases
    socks5:
        image: jinnlynn/shadowsocks
        logging: *logging
        restart: always
        depends_on:
            - kcptun
        networks:
            freegate:
                ipv4_address: 172.27.0.12
        ports:
            - 9527:1080
            - 9527:1080/udp
        volumes:
            - ${KITS}/etc/shadowsocks:/app/etc
        command: ss-local $SS_SERVER $SS_AUTH $SS_ARGS -l 1080
    polipo:
        image: jinnlynn/polipo
        logging: *logging
        restart: always
        depends_on:
            - socks5
        networks:
            - freegate
        ports:
            - 9580:8123
        command:
            - socksProxyType=socks5
            - socksParentProxy=172.27.0.12:1080
networks:
    freegate:
        driver: bridge
        ipam:
            config:
                - subnet: 172.27.0.0/24
