# 翻墙 服务器端 172.27.0.x
version: "3.8"
x-logging: &logging
    options:
        max-size: 10m
services:
    ss:
        image: jinnlynn/shadowsocks
        logging: *logging
        restart: always
        networks:
            freegate:
                ipv4_address: 172.27.0.10
        ports:
            - 8380-8381:8380-8381
            - 8380-8381:8380-8381/udp
        volumes:
            - ${KITS}/etc/shadowsocks/:/app/etc/
        # command: ss-server -s 0.0.0.0 -p 8380 $SS_AUTH $SS_ARGS
        # command: ["ss-server", "-c", "/app/etc/config.json", "-v"]
        # 配置的manager_address未生效 源代码中已有，下一个版本可用
        command: ["ss-manager", "-c", "/app/etc/config.json", "--manager-address", "0.0.0.0:8390"]
    # ss-alone:
    #     image: jinnlynn/shadowsocks
    #     logging: *logging
    #     restart: always
    #     networks:
    #         freegate:
    #             ipv4_address: 172.27.0.12
    #     ports:
    #         - 57710:8388
    #         - 57710:8388/udp
    #     command: ss-server -s 0.0.0.0 -p 8388 $SS_AUTH $SS_ARGS_NO_PLUGIN
    ssk:
        image: jinnlynn/kcptun
        logging: *logging
        restart: always
        networks:
            - freegate
        depends_on:
            - ss
        ports:
            - 29900:29900/udp
        command: kcptun-server --target 172.27.0.10:8380 $KCPTUN_ARGS
    vpn:
        image: hwdsl2/ipsec-vpn-server
        logging: *logging
        restart: always
        privileged: true
        networks:
            - freegate
        environment:
            - VPN_USER
            - VPN_PASSWORD
            - VPN_IPSEC_PSK
        ports:
            - 500:500/udp
            - 4500:4500/udp
        volumes:
            - /lib/modules:/lib/modules:ro
networks:
    freegate:
        driver: bridge
        ipam:
            config:
                - subnet: 172.27.0.0/24
