# 服务器上运行的服务（翻墙）
# sks:  kcptun、shadowsocks-libev 最新版本
# s2ks: kcptun、shadowsocks-libev 2.5.6 开启OTA
# vpn: IPSec VPN
# vnstat: 流量
version: '3'
services:
    ss:
        image: jinnlynn/shadowsocks
        restart: always
        networks:
            default:
                ipv4_address: 10.0.0.11
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 57700:8388
            - 57700:8388/udp
    ssk:
        image: jinnlynn/kcptun
        restart: always
        depends_on:
            - ss
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 55800:29900/udp
        command: server_linux_amd64 --target 10.0.0.11:8388 $KCPTUN_ARGS
    ss2:
        image: jinnlynn/shadowsocks:2.5.6
        restart: always
        networks:
            default:
                ipv4_address: 10.0.0.12
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 57701:8388
            - 57701:8388/udp
    ss2k:
        image: jinnlynn/kcptun
        restart: always
        depends_on:
            - ss2
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 55801:29900/udp
        command: server_linux_amd64 --target 10.0.0.12:8388 $KCPTUN_ARGS
    ssh-kcp:
        image: jinnlynn/kcptun
        restart: always
        network_mode: host
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 55802:29900/udp
        command: server_linux_amd64 --target 127.0.0.1:22 $KCPTUN_ARGS
    vpn:
        image: hwdsl2/ipsec-vpn-server
        restart: always
        privileged: true
        env_file: ${KITS}/etc/docker/env.ini
        ports:
            - 500:500/udp
            - 4500:4500/udp
        volumes:
            - /lib/modules:/lib/modules:ro
    vnstat:
        image: jinnlynn/vnstat
        restart: always
        network_mode: host
        volumes:
            - /var/lib/vnstat:/var/lib/vnstat
    nginx:
        image: jinnlynn/nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${KITS}/etc/nginx/conf.d:/etc/nginx/conf.d
            - ${KITS}/etc/nginx/certs:/etc/nginx/certs
            - ${KITS}/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ${KITS}/share/www:/var/www
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24
