# 树莓派网关上运行的服务 172.16.10.11 -
# 翻墙(匿名代理): gfw-client.yml, 同时加载即可
# 其它服务:
# 内网穿透客户端  流量统计 下载    web   git     DLNA      dnsmasq配置监控更新
# frpc          vnstat  aria2  nginx  gitsrv  minidlna  dnsmasq-conf
version: "3"
services:
    frpc:
        image: jinnlynn/frp
        restart: always
        network_mode: host
        depends_on:
            - dnsmasq
        volumes:
            - ${KITS}/etc/frp:/app/etc
        command: frpc -c /app/etc/frpc.ini
    ddns:
        image: jinnlynn/ddns
        restart: always
        environment:
            - DDNS_TOKEN
            - DDNS_DOMAIN
            - DDNS_IP_SERVICE
            - DDNS_CHECK_INTERVAL
        logging:
            options:
                max-size: 1m
    dnsmasq-conf:
        image: jinnlynn/genpac-watch
        restart: always
        environment:
            - GPW_REMOTE
            - GPW_TOKEN
            - GPW_CONTAINER
        logging:
            options:
                max-size: 1m
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${KITS_LOCAL}/genpac/dnsmasq.conf:/app/local/dnsmasq.conf
    vnstat:
        image: jinnlynn/vnstat
        restart: always
        #! 必须
        network_mode: host
        volumes:
            - ${KITS_LOCAL}/vnstat:/var/lib/vnstat
    nginx:
        image: jinnlynn/nginx
        restart: always
        logging:
            options:
                max-size: 1m
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${KITS}/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ${KITS_LOCAL}/dehydrated/certs:/etc/nginx/certs

    # gogs:
    #     image: jinnlynn/gogs:armhf
    #     restart: always
    #     networks:
    #         default:
    #             ipv4_address: 172.16.10.12
    #     ports:
    #         # - "9980:3000" # web 端口不外放 通过nginx反向代理
    #         - "9922:2222"
    #     volumes:
    #         - ${KITS}/etc/gogs:/app/etc
    #         - ${KITS_LOCAL}/gogs:/app/local
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.10.0/24
