# 树莓派网关上运行的服务
# 翻墙(匿名代理): gfw-client.yml, 同时加载即可
# 其它服务:
# 流量统计 下载    web    git     DLNA      dnsmasq配置监控更新
# vnstat  aria2  nginx  gitsrv  minidlna  dnsmasq-conf
version: "3"
services:
    dnsmasq-conf:
        image: jinnlynn/genpac-watch:armhf
        restart: always
        environment:
            - GPW_REMOTE
            - GPW_TOKEN
            - GPW_CONTAINER
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${KITS_LOCAL}/genpac/dnsmasq.conf:/app/local/dnsmasq.conf
    vnstat:
        image: jinnlynn/vnstat:armhf
        restart: always
        #! 必须
        network_mode: host
        volumes:
            - ${KITS_LOCAL}/vnstat:/var/lib/vnstat
    aria2:
        image: jinnlynn/aria2:armhf
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.16.0.11
        ports:
            - 6900:6900
            - 6901:6901/udp
        volumes:
            - ${KITS}/etc/aria2:/app/etc
            - ${KITS}/var/run/aria2:/app/run
            - /cellar/mnt/download/aria2:/app/local
    nginx:
        image: jinnlynn/nginx:armhf
        restart: always
        ports:
            - 6800:6800
            - 5580:5580
        volumes:
            - ${KITS}/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ${KITS_LOCAL}/dehydrated/certs:/etc/nginx/certs
    gitsrv:
        image: jinnlynn/git-server:armhf
        restart: always
        ports:
            - "5448:22" # 双引号去掉会出错, WHY
        volumes:
            - /cellar/mnt/repo/git:/app/local
            - ${KITS}/etc/docker/jkey.pub:/app/etc/jkey.pub
            - /etc/ssh/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key
            - /etc/ssh/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key
            - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
            - /etc/ssh/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    minidlna:
        image: jinnlynn/minidlna:armhf
        restart: always
        network_mode: host
        volumes:
            - /cellar/mnt/media:/app/opt/media
            - ${KITS_LOCAL}/minidlna:/app/local
            - ${KITS}/var/log:/app/log
    bypy:
        image: jinnlynn/bypy:armhf
        restart: always
        volumes:
            - ${KITS_LOCAL}/bypy:/root/.bypy
            - /cellar/mnt/media:/app/opt/nas-media
            - /cellar/mnt/documents/Shared/Software:/app/opt/nas-apps
volumes:
    vdata:
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24
