# 服务器上运行的服务 172.16.10.11 -
# 翻墙(shadowsocks vpn): gfw-server.yml 同时加载即可
# 网页: web.yml
# 其它服务
# 内网穿透服务端  流量    ssh加速
# frps          vnstat  ssh-kcp
version: "3.8"
x-logging: &logging
    options:
        max-size: 10m
services:
    vnstat:
        image: jinnlynn/vnstat
        logging: *logging
        restart: always
        network_mode: host
        volumes:
            - /var/lib/vnstat:/var/lib/vnstat
    frps:
        image: jinnlynn/frp
        logging: *logging
        restart: always
        networks:
            default:
                ipv4_address: 172.27.1.11
        ports:
            - "7000:7000"
            - "7000:7000/udp"
            - "7001:7001/udp"
            # - "7500:7500"
            - "5522-5525:5522-5525"
            - "5522-5525:5522-5525/udp"
            - "5534:5534"
            # CORP
            - "5622:5622"
        volumes:
            - ${KITS}/etc/frp:/app/etc
        command: ["frps", "-c", "/app/etc/frps.ini"]
    # aria2:
    #     image: jinnlynn/aria2
    #     restart: unless-stopped
    #     networks:
    #         default:
    #             ipv4_address: 172.27.1.13
    #     logging: *logging
    #     environment:
    #         - A2_DOWNLOAD_PATH=/app/mnt/download
    #         - A2_DOWNLOAD_COMPLETE_DST=/app/mnt/done
    #     ports:
    #         - 6900:6900
    #         - 6900:6900/udp
    #         - 6901:6901
    #         - 6901:6901/udp
    #     volumes:
    #         - ${KITS}/etc/aria2:/app/etc
    #         - ${KITS_LOCAL}/aria2:/app/local
    #         - /cellar/data/download:/app/mnt/download
    #         - /cellar/data/done:/app/mnt/done
    #     command: ["--conf-path=/app/etc/aria2.conf"]
    # registry:
    #     image: registry
    #     restart: always
    #     networks:
    #         default:
    #             ipv4_address: 172.27.1.14
    #     logging: *logging
    #     volumes:
    #         - ${KITS_LOCAL}/registry:/var/lib/registry
    # cloudcmd:
    #     image: jinnlynn/cloudcmd
    #     restart: unless-stopped
    #     networks:
    #         default:
    #             ipv4_address: 172.27.1.15
    #     logging: *logging
    #     volumes:
    #         - ${KITS}/etc/cloudcmd/:/app/etc/
    #         - /cellar:/app/mnt/data
    #     command: ["--config", "/app/etc/config.json"]
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.27.1.0/24
