# 服务器上运行的服务
# 翻墙(shadowsocks vpn): gfw-server.yml 同时加载即可
# 网页: web.yml
# 其它服务
# 流量     web    ssh加速
# vnstat  nginx  ssh-kcp
version: "3"
services:
    ssh-kcp:
        image: jinnlynn/kcptun
        restart: always
        network_mode: host
        ports:
            - 55802:29900/udp
        command: server_linux_amd64 --target 127.0.0.1:22 $KCPTUN_ARGS
    vnstat:
        image: jinnlynn/vnstat
        restart: always
        network_mode: host
        volumes:
            - /var/lib/vnstat:/var/lib/vnstat
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.0.0/24
