version: "3"
services:
    nginx:
        image: jinnlynn/nginx
        restart: always
        logging:
            options:
                max-size: 1m
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${KITS}/etc/nginx/conf.d:/etc/nginx/conf.d
            - ${KITS}/etc/nginx/certs:/etc/nginx/certs
            - ${KITS}/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - ${KITS}/etc/nginx/snippets:/etc/nginx/snippets
            - ${KITS}/share/www:/var/www
    genpac:
        image: jinnlynn/genpac-server:dev
        restart: always
        networks:
            default:
                ipv4_address: 172.16.0.21
        logging:
            options:
                max-size: 1m
        environment:
            GENPAC_CONFIG: /app/etc/config.ini
        volumes:
            - ${KITS}/share/genpac:/app/opt/genpac
            - ${KITS}/share/genpac-server:/app/opt/genpac-server
            - ${KITS}/etc/genpac:/app/etc
            - ${KITS_VAR}/local/genpac:/app/var/local
    ariang:
        image: jinnlynn/ariang
        restart: always
        networks:
            default:
                ipv4_address: 172.16.0.22
        logging:
            options:
                max-size: 1m
    alimama:
        image: jinnlynn/alimama
        build: ${KITS}/share/apps/alimama
        restart: always
        networks:
            default:
                ipv4_address: 172.16.0.23
        logging:
            options:
                max-size: 1m
        volumes:
            - ${KITS}/share/apps/alimama/links.txt:/app/opt/links.txt
    toolkit:
        image: jinnlynn/toolkit
        build: ${KITS}/share/apps/toolkit
        restart: always
        networks:
            default:
                ipv4_address: 172.16.0.24
        logging:
            options:
                max-size: 1m
        environment:
            - LANG
            - LC_ALL
            - LC_CTYPE
            - LANGUAGE
