# web 应用 172.27.1.2x
version: "3.8"
x-logging: &logging
    options:
        max-size: 10m
services:
    genpac:
        image: jinnlynn/flask:py2
        logging: *logging
        restart: unless-stopped
        networks:
            net-web:
                ipv4_address: 172.22.1.10
        environment:
            GENPAC_CONFIG: /app/etc/config.ini
        volumes:
            - ${KITS}/opt/genpac:/app/opt/genpac
            - ${KITS}/opt/genpac-server:/app/opt/genpac-server
            - ${KITS}/etc/genpac:/app/etc
            - ${KITS_LOCAL}/genpac:/app/local
            - ${KITS}/etc/genpac/server-start.sh:/app/bin/server-start
        command: ["server-start"]
    ariang:
        image: jinnlynn/ariang
        logging: *logging
        restart: unless-stopped
        networks:
            net-web:
                ipv4_address: 172.22.1.11
    file:
        image: jinnlynn/nginx:fancyindex
        logging: *logging
        restart: unless-stopped
        networks:
            net-web:
                ipv4_address: 172.22.1.12
        volumes:
            - ${KITS}/share/public-keys/:/app/mnt/keys/
    toolkit:
        image: jinnlynn/flask
        logging: *logging
        restart: unless-stopped
        networks:
            net-web:
                ipv4_address: 172.22.1.13
        environment:
            - LANG
            - LC_ALL
            - LC_CTYPE
            - LANGUAGE
        volumes:
            - ${KITS}/opt/toolkit:/app/opt
    httpbin:
        image: jinnlynn/httpbin
        logging: *logging
        restart: unless-stopped
        networks:
            net-web:
                ipv4_address: 172.22.1.20
        environment:
            - UWSGI_MOUNT=/http=httpbin:app
networks:
    net-web:
        driver: bridge
        ipam:
            config:
                - subnet: 172.22.1.0/24
