name: Build and Push
description: Build Image and Push it to docker hub
inputs:
  username:
    description: Username for image registry
    required: true
  password:
    description: Password for image registry
    required: true
  image:
    description: Image for build
    default: ""
    required: false
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
    - uses: actions/checkout@v4
    - shell: bash
      run: chmod +x ./build
    - name: Build and Push
      if: ${{ inputs.image != '' }}
      shell: bash
      run: ./build -v -p ${{ inputs.image }}
