# alpine 3.7 httpd被移到busybox-extras中
# https://git.alpinelinux.org/cgit/aports/commit/main/busybox?id=23f4c6bd6c0c8c8f616facad94865e7961cdfb2d
#
FROM jinnlynn/alpine:armhf

LABEL maintainer="JinnLynn <eatfishlin@gmail.com>"

RUN set -ex && \
    apk add --no-cache busybox-extras && \
    echo -e "A:*\n.js:application/javascript" >/etc/httpd.conf && \
    mkdir -p /app/var/www && \
    echo "it's work." >/app/var/www/index.html

EXPOSE 80

WORKDIR /app/var/www

CMD ["httpd", "-f", "-vv"]
