# 使用方法:
# docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock jinnlynn/ctop:armhf
FROM jinnlynn/alpine:armhf

LABEL maintainer="JinnLynn <eatfishlin@gmail.com>"

ARG CTOP_VER="0.7"
ARG CTOP_URL="https://github.com/bcicen/ctop/releases/download/v$CTOP_VER/ctop-$CTOP_VER-linux-arm"

RUN set -ex && \
    apk add --no-cache curl && \
    curl -SL -o /app/bin/ctop $CTOP_URL && \
    chmod +x /app/bin/ctop && \
    apk del --no-cache curl

CMD ctop
