FROM jinnlynn/alpine:armhf

LABEL maintainer="JinnLynn <eatfishlin@gmail.com>"

ARG MIRROR="https://mirrors.ustc.edu.cn/pypi/web/simple"

RUN set -ex && \
    apk add --no-cache python py2-pip && \
    mkdir -p /root/.pip && \
    echo -e "[global]\nindex-url = $MIRROR" >/root/.pip/pip.conf && \
    pip install --no-cache-dir -U pip

CMD ["python", "--version"]
