#!/bin/sh
set -e

BRANCH="v3.6"
VERSION="3.6.2"
MIRROR="${MIRROR:-https://mirrors.ustc.edu.cn/alpine}"
TIMEZONE="${TIMEZONE-Asia/Shanghai}"
APP_DIRS="bin etc opt mnt local log run tmp var"

if [ "$MIRROR" ]; then
    {
        echo "$MIRROR/$BRANCH/main"
        echo "$MIRROR/$BRANCH/community"
        if [ "$BRANCH" == "edge" ]; then
            echo "$MIRROR/$BRANCH/testing"
        fi
    } >/etc/apk/repositories
fi

if [ "$TIMEZONE" ]; then
    apk add --no-cache tzdata
    cp "/usr/share/zoneinfo/$TIMEZONE" "/etc/localtime"
    apk del --no-cache tzdata
fi

if [ "$APP_DIRS" ]; then
    # alpine mkdir 不支持mkdir -p /app/{...}
    for d in $APP_DIRS; do mkdir -p /app/$d; done
fi

exit 0
