FROM jinnlynn/python:armhf

MAINTAINER JinnLynn <eatfishlin@gmail.com>

RUN set -ex && \
    pip install -U pip youtube-dl && \
    apk add --no-cache ffmpeg ca-certificates

ENTRYPOINT ["youtube-dl"]

CMD ["--help"]
