name: Automatic Build Image:edge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"

jobs:
  alpine:
    uses: ./.github/workflows/build-single.yml
    with:
      image: alpine
      target: edge
    secrets: inherit
  ubuntu:
    uses: ./.github/workflows/build-single.yml
    with:
      image: ubuntu
      target: edge
    secrets: inherit
