name: build-single

on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ''
      target:
        required: false
        type: string
        default: ''
      extra_target:
        required: false
        type: string
        default: ''
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
          required: true
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v4
      - run: chmod +x ./build
      - name: Build and Push
        if: ${{ inputs.image != '' }}
        run: ./build -v -p ${{ inputs.target && format('-t {0}', inputs.target) }} ${{ inputs.image }}
      - name: Build extra
        if: ${{ success() && inputs.image && inputs.extra_target }}
        run: ./build -v -p -t ${{ inputs.extra_target }} ${{ inputs.image }}
