name: Build and Push Image
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'alpine/**'
      - 'ubuntu/**'
      - 'python/**'
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      alpine: ${{ steps.filter.outputs.alpine }}
      ubuntu: ${{ steps.filter.outputs.ubuntu }}
      python: ${{ steps.filter.outputs.python }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            alpine: 'alpine/**'
            ubuntu: 'ubuntu/**'
            python: 'python/**'
  alpine:
    if: ${{ needs.changes.outputs.alpine == 'true' }}
    needs: changes
    uses: JinnLynn/dockerfiles/.github/workflows/build-single.yml@master
    with:
      image: alpine
      extra_build_target: gnu
    secrets: inherit
  # alpine:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.alpine == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: JinnLynn/dockerfiles/.github/actions/docker-build-push@master
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME}}
  #         password: ${{ secrets.DOCKER_TOKEN}}
  #         image: alpine
  #     - name: Build alpine:gnu
  #       run: ./build -v -p -t gnu alpine
  # ubuntu:
  #   needs: changes
  #   if: ${{ needs.changes.outputs.ubuntu == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: JinnLynn/dockerfiles/.github/actions/docker-build-push@master
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME}}
  #         password: ${{ secrets.DOCKER_TOKEN}}
  #         image: ubuntu
  # python:
  #   needs: [changes, alpine]
  #   if: ${{ needs.changes.outputs.python == 'true' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: JinnLynn/dockerfiles/.github/actions/docker-build-push@master
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME}}
  #         password: ${{ secrets.DOCKER_TOKEN}}
  #         image: python

