name: Build and Push Image
on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        required: false
      target:
        type: string
        required: false
  push:
    branches:
      - master
    # paths:
    #   - 'alpine/**'
    #   - 'ubuntu/**'
    #   - 'python/**'
env:
  base: '["alpine", "ubuntu", "python", "node"]'
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      base: ${{ env.base }}
      alpine: ${{ steps.filter.outputs.alpine }}
      ubuntu: ${{ steps.filter.outputs.ubuntu }}
      python: ${{ steps.filter.outputs.python }}
      node: ${{ steps.filter.outputs.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            alpine: 'alpine/**'
            ubuntu: 'ubuntu/**'
            python: 'python/**'
            node: 'node/**'
  alpine:
    if: ${{ needs.changes.outputs.alpine == 'true' || inputs.image == 'alpine' }}
    needs: changes
    uses: ./.github/workflows/build-single.yml
    with:
      image: alpine
      target: ${{ inputs.target }}
      extra_target: ${{ ! inputs.target && 'gnu' }}
    secrets: inherit
  ubuntu:
    if: ${{ needs.changes.outputs.ubuntu == 'true' || inputs.image == 'ubuntu' }}
    needs: changes
    uses: ./.github/workflows/build-single.yml
    with:
      image: ubuntu
    secrets: inherit
  python:
    if:  |
      always() &&
      needs.alpine.result != 'failure' &&
      ( needs.changes.outputs.python == 'true' || inputs.image == 'python' )
    needs: [changes, alpine]
    uses: ./.github/workflows/build-single.yml
    with:
      image: python
    secrets: inherit
  node:
    if:  |
      always() &&
      needs.alpine.result != 'failure' &&
      ( needs.changes.outputs.node == 'true' || inputs.image == 'node' )
    needs: [changes, alpine]
    uses: ./.github/workflows/build-single.yml
    with:
      image: node
    secrets: inherit
  specified:
    if: ${{ inputs.image && !contains(fromJSON(needs.changes.outputs.base), inputs.image) }}
    needs: changes
    uses: ./.github/workflows/build-single.yml
    with:
      image: ${{ inputs.image }}
      target: ${{ inputs.target }}
    secrets: inherit
