name: Reusable Build Single Image

on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ''
      extra_build_target:
        required: false
        type: string
        default: ''
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v4
      - shell: bash
        run: chmod +x ./build
      - name: Build and Push
        if: ${{ inputs.image != '' }}
        shell: bash
        run: ./build -v -p ${{ inputs.image }}
      - name: Build extra
        if: ${{ inputs.image != '' && inputs.extra_build_target != '' }}
        shell: bash
        run: ./build -v -p -t ${{ inputs.extra_build_target }} ${{ inputs.image }}
